Repository canvas-gamification/canvas-gamification, pull requests merged in 2020-09, with the labels that each got.

#17 Update readme
  README.rst
Labels: documentation

#19 Update read me and add dev environment
  README.rst
  accounts/forms.py
  accounts/tests.py
  canvas_gamification/settings.py
  docker-compose.dev.yml
  env/gamification.dev.env
  utils/__init__.py
  utils/recaptcha.py
Labels: documentation

#20 add mock course
  canvas/canvasapi_mock.py
  canvas/migrations/0005_canvascourse_mock.py
  canvas/models.py
  canvas/tests.py
Labels: enhancement

#21 Add Junit Test Support for Java Questions
  course/forms/forms.py
  course/forms/java.py
  course/forms/parsons.py
  course/grader.py
  course/management/commands/populate-db.py
  course/migrations/0006_auto_20200921_2020.py
  course/models/models.py
  course/models/parsons_question.py
  course/tests.py
  course/utils/utils.py
  import/java_questions.json
Labels: enhancement

#24 added event column to problem set
  canvas/models.py
  course/templates/problem_set.html
Labels: enhancement, good first issue

#27 Fix servername in nginx
  env/nginx.conf
Labels: bug

#28 Fix email links
  canvas_gamification/settings.py
  env/gamification.sample.env
  env/nginx.conf
Labels: bug

#31 Renamed event column in problem set to Type
  course/templates/problem_set.html
Labels: enhancement

#32 Added event selection to question creation page
  course/forms/forms.py
  course/forms/java.py
  course/forms/multiple_choice.py
  course/forms/parsons.py
  course/utils/utils.py
  course/views/multiple_choice.py
Labels: enhancement

#35 Added button to edit question from event page
  canvas/templates/canvas/problem_set_snippet.html
Labels: enhancement

#25 Update registration
  canvas/templates/canvas/course_registration.html
  canvas/views/register_views.py
Labels: enhancement, good first issue
