Repository canvas-gamification/canvas-gamification, pull requests merged in 2021-06, with the labels that each got.

#183 Support Ordering of Question Submissions
  api/views/submission.py
Labels: bug, enhancement

#185 Add is_author field to Questions
  api/serializers/question.py
Labels: bug

#181 Reset password
  accounts/templates/accounts/password_reset_email.html
  accounts/utils/email_functions.py
  api/serializers/__init__.py
  api/serializers/change_password.py
  api/serializers/reset_password.py
  api/urls.py
  api/views/__init__.py
  api/views/change_password.py
  api/views/reset_password.py
Labels: enhancement

#189 Update README.rst
  README.rst
Labels: bug, documentation

#197 Update User Consent Permission
  api/permissions.py
  api/views/question.py
  api/views/user_consent.py
Labels: bug

#190 Add Support for Checkbox Questions
  api/serializers/multiple_choice_question.py
  api/serializers/uqj.py
  course/admin.py
  course/forms/multiple_choice.py
  course/grader/grader.py
  course/migrations/0013_delete_checkboxquestion.py
  course/models/models.py
  course/urls.py
  course/views/views.py
  templates/navbar.html
Labels: enhancement

#196 Added django action for custom serializing all questions ready for export
  api/views/question.py
Labels: enhancement

#200 Changed UQJ filters to match ESLint naming conventions
  api/views/uqj.py
Labels: bug, refactor
