Repository canvas-gamification/canvas-gamification, pull requests merged in 2021-07, with the labels that each got.

#204 Update MCQ Checkbox Grader
  course/grader/grader.py
  course/tests.py
  course/utils/utils.py
Labels: bug

#205 Add Error Message Classes
  api/error_messages/__init__.py
  api/error_messages/additional_file_name.py
  api/error_messages/answer.py
  api/error_messages/category.py
  api/error_messages/course.py
  api/error_messages/difficulty.py
  api/error_messages/event.py
  api/error_messages/input_file_names.py
  api/error_messages/junit_template.py
  api/error_messages/lines.py
  api/error_messages/max_submission_allowed.py
  api/error_messages/question.py
  api/error_messages/schema.py
  api/error_messages/submission.py
  api/error_messages/text.py
  api/error_messages/title.py
  api/error_messages/visible_distractor_count.py
  api/serializers/java_question.py
  api/serializers/multiple_choice_question.py
  api/serializers/parsons_question.py
  api/views/schema.py
  api/views/submission.py
Labels: refactor

#211 Fixes Bug with Accidental Expecting Integer in Event Field
  api/serializers/java_question.py
  api/serializers/multiple_choice_question.py
  api/serializers/parsons_question.py
Labels: bug

#218 Fixed schema title for styling
  course/templates/schemas/java_input_files.json
  course/templates/schemas/parsons_input_files.json
  course/templates/schemas/variables.json
Labels: enhancement

#222 Course Module Backend Update
  api/error_messages/__init__.py
  api/error_messages/course_registration.py
  api/error_messages/token_use.py
  api/error_messages/user.py
  api/views/course.py
  api/views/token_use.py
Labels: enhancement

#213 Deleted Question gets Flagged
  api/views/question.py
  api/views/uqj.py
  course/migrations/0020_question_question_status.py
  course/models/models.py
Labels: enhancement
