Repository canvas-gamification/canvas-gamification, pull requests merged in 2021-05, with the labels that each got.

#167 Update User Stats Permissions
  api/views/user_stats.py
Labels: bug

#170 Added functionality to auto-assign author on question create
  api/views/java_question.py
  api/views/multiple_choice_question.py
  api/views/parsons_question.py
Labels: bug

#172 Fix UQJ Permissions
  api/views/uqj.py
Labels: bug

#174 Removing use of "registered" for permissions in the Course API
  api/permissions.py
  api/serializers/__init__.py
  api/serializers/course.py
  api/views/course.py
Labels: refactor

#179 Update README
  README.rst
Labels: documentation
