Repository canvas-gamification/canvas-gamification, pull requests merged in 2021-08, with the labels that each got.

#228 Add more names to variables schema
  course/utils/variables.py
Labels: enhancement

#219 Import Events
  api/permissions.py
  api/views/event.py
  canvas/models.py
  course/models/models.py
Labels: enhancement

#230 Update User Consent Model to Support New Fields
  accounts/migrations/0014_auto_20210811_1303.py
  accounts/models.py
  api/serializers/user_consent.py
Labels: refactor

#226 API Errors: Update Api Responses
  api/views/question.py
  api/views/register.py
  api/views/reset_password.py
  api/views/submission.py
  api/views/token_use.py
Labels: bug
