Repository canvas-gamification/canvas-gamification, pull requests merged in 2022-04, with the labels that each got.

#292 update Junit to latest release
  course/grader/canvas-gamification-junit-tests.jar
Labels: enhancement

#294 Verified Filter
  api/views/uqj.py
Labels: bug

#298 Remove Status Class
  api/serializers/uqj.py
  course/models/models.py
Labels: refactor

#296 Create parent_category filter for UQJs
  api/views/uqj.py
Labels: enhancement

#301 Fix UQJ Status in the Backend
  course/models/models.py
Labels: bug
